### ISSUE TITLE
./stream.sh: line 13: ffmpeg: command not found

### ISSUE THREAD

**Issue by neonny0** [simsimler/youtube-stream#3]
기본 환경을 구축하기 위해 ``git bash``을 사용하여 ``stream.sh``을 열어보았지만 위 제목과 같은 오류가 발생합니다. ffmpeg의 명령어가 올바르기 위해 어떤 조치을 취해야 합니까? (Windows 운영체제)

**Comment by simsimler** [comment]
ffmpeg를 PATH에 추가하셨나요?

**Comment by neonny0** [comment]
> ffmpeg를 PATH에 추가하셨나요?

확인해보도록 하겠습니다.

**Comment by neonny0** [comment]
> ffmpeg를 PATH에 추가하셨나요?

똑같은 결과 값이 나옵니다

**Comment by simsimler** [comment]
Git bash를 재시작해보셨나요

**Comment by simsimler** [comment]
![image](https://user-images.githubusercontent.com/72448769/125237581-e37cd600-e320-11eb-820b-9e335af4710c.png)
저의 경우 재현이 불가능합니다.

**Comment by neonny0** [comment]
우선적으로 wsl을 이용해 올바르게 사용했습니다.
